次のコードがあります。

public class Main {
    public static void main(String[] args) throws Exception {
        x();
        System.out.print("1 ");
    }
    static void x() throws Exception {
        if (Math.random() > 0.1) { throw new Exception();}
        System.out.print("2 ");
    }
}

コンパイル、実行した結果として正しいものは次のどれですか。2つ選択してください。

A. Exception in thread "main" java.lang.Exception
    at Main.x(Main.java:7)
    at Main.main(Main.java:3)
   1
B. 1
   Exception in thread "main" java.lang.Exception
    at Main.x(Main.java:7)
    at Main.main(Main.java:3)
C. Exception in thread "main" java.lang.Exception
    at Main.x(Main.java:7)
    at Main.main(Main.java:3)
D. 2 1
E. 1 2
